public class Main {
    public static void main(String[] args) {
        EmployeeBook employeeBook = new EmployeeBook();
        employeeBook.createEmployee("Иванов Иван Иванович", 1, 1000);
        employeeBook.createEmployee("Семенов Семен Семенович", 1, 2000);
        employeeBook.createEmployee("Сергеев Сергей Сергеевич", 2, 3000);
        employeeBook.createEmployee("Федоров Федор Федорович", 2, 4000);
        employeeBook.createEmployee("Максимов Максим Максимыч", 3, 5000);
        employeeBook.createEmployee("Алексеев Алексей Алексеевич", 3, 6000);
        employeeBook.createEmployee("Михайлов Михаил Михайлович", 4, 7000);
        employeeBook.createEmployee("Эдуардов Эдуард Эдуардович", 4, 8000);
        employeeBook.createEmployee("Николаев Николоай Николаевич", 5, 9000);
        employeeBook.createEmployee("Владимиров Владимир Владиморович", 5, 10000);
        employeeBook.createEmployee("Евгенье Евгений Евгеньевич", 5, 11000);
        System.out.println();
        System.out.println("Список всех сотрудников");
        employeeBook.printEmployees();
        System.out.println();
        System.out.println("Изменяем зарплату сотрудникам");
        employeeBook.increaseSalary(1);
        System.out.println();
        System.out.println("Общая сумма зарплаты сотрудников всех отделов - " + employeeBook.calculateTotalSalary());
        System.out.println();
        System.out.println("Сотрудник с минимальной зарплатой - " + employeeBook.findEmployeeWitchMinSalary());
        System.out.println();
        System.out.println("Сотрудник с максимальной зарплатой - " + employeeBook.findEmployeeWitchMaxSalary());
        System.out.println();
        System.out.println("Средняя зарплата сотрудников всех отделов - " + employeeBook.calculateAverageSalary());
        System.out.println();
        System.out.println("Сотрудник с минимальной зарплатой в первом отделе - " + employeeBook.findEmployeeWitchMinSalaryByDepartment(1));
        System.out.println();
        System.out.println("Сотрудник с максимальной зарплатой во втором отделе - " + employeeBook.findEmployeeWitchMaxSalaryByDepartment(2));
        System.out.println();
        System.out.println("Зарплата 3тьего отдела - " + employeeBook.calculateTotalSalaryOfDepartment(3));
        System.out.println();
        System.out.println("Средняя зарплата по 4ветому отделу - " + employeeBook.calculateAverageSalaryOfDepartment(4));
        employeeBook.increaseSalaryDepartment(5,1);
        System.out.println();
        System.out.println("Сотрудники 5того отдела - ");
        employeeBook.printEmployeesOfDepartment(5);
        System.out.println();
        System.out.println("Сотрудники с зарплатой меньше 2000 - ");
        employeeBook.printEmployeesWithMinSalary(2000);
        System.out.println();
        System.out.println("Сотрудники с зарплатой больше 9000 - ");
        employeeBook.printEmployeesWithMaxSalary(9000);
        System.out.println();
        System.out.println("Ф.И.О сотрудников по отделам - ");
        employeeBook.printEmployeeByDepartments();
        System.out.println();
        System.out.println("Меняем депортамент сотрдудника Сергеев Сергей Сергеевич по депортаменту");
        employeeBook.changeDepartment("Сергеев Сергей Сергеевич",2);
        System.out.println();
        System.out.println("Меняем зарплату сотрдудника Сергеев Сергей Сергеевич по зарплате");
        employeeBook.changeSalary("Сергеев Сергей Сергеевич",5555);
        System.out.println();
        System.out.println("Список всех сотрудников");
        employeeBook.printEmployees();
        System.out.println("Удаляем сотрудника Эдуардов Эдуард Эдуардович по nick");
        employeeBook.removeEmployee("Эдуардов Эдуард Эдуардович");
        System.out.println();
        System.out.println("Удаляем сотрудника Алексеев Алексей Алексеевич по id");
        employeeBook.removeEmployeeId(6);
        System.out.println();
        System.out.println("Список всех сотрудников");
        employeeBook.printEmployees();
    }
}
